name: Send Bluesky Post

on: [push]

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Send Bluesky Post
        uses: myConsciousness/bluesky-post@v5
        with:
          text: "${{ github.event.head_commit.message }} van @kleineboodschap.com is toegevoegd aan Kleine Boodschap Data. Bekijk alle statistieken op https://sjorshartwijk.github.io/kleineboodschap/ #kleineboodschap"
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{ secrets.BLUESKY_PASSWORD }}
          retry-count: 5
