name: Send Bluesky Post

on:
  push:
    paths:
      - 'episodes.json'

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Send Bluesky Post
        uses: myConsciousness/bluesky-post@v5
        with:
            text: "${{ github.event.head_commit.message }} van @kleineboodschap.com is toegevoegd aan Kleine Boodschap Data.\nBekijk alle statistieken op www.kbdata.nl \n\n#kleineboodschap"
            identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
            password: ${{ secrets.BLUESKY_PASSWORD }}
            retry-count: 5
