name: Post Kleine Boodschap Bericht

on:
  schedule:
    # 1e van de maand om 09:50 NL tijd (08:50 UTC)
    - cron: "50 8 1 * *"
  workflow_dispatch: # ook handmatig te triggeren

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests python-dateutil

      - name: Build message
        id: build
        run: |
          python .github/scripts/build_message.py > message.txt

      - name: Show built message (debug)
        run: cat message.txt

      - name: Post to Bluesky
        uses: myConsciousness/bluesky-post@v5
        with:
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{ secrets.BLUESKY_PASSWORD }}
          text: |
            ${{ steps.build.outputs.message }}
