name: Post monthly Kleine Boodschap stats to Bluesky

on:
  schedule:
    - cron: '0 9 1 * *' # Elke 1e van de maand om 09:00 UTC = 11:00 CEST

jobs:
  post-bluesky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Debug episodes.json presence en inhoud
        run: |
          echo "Inhoud van huidige map:"
          ls -la
          echo "Inhoud van episodes.json:"
          cat episodes.json

      - name: Controleer of episodes.json geldig is
        run: |
          if ! [ -s episodes.json ]; then
            echo "Fout: episodes.json ontbreekt of is leeg" >&2
            exit 1
          fi
          jq . episodes.json

      - name: Read episodes.json and compose message
        id: compose
        run: |
          month=$(date --utc +'%B %Y' -d 'now -1 month')
          data=$(cat episodes.json)
          luistertijd=$(echo "$data" | jq -r '.total_listening_time')
          interview=$(echo "$data" | jq -r '.categories.interview')
          achtergrond=$(echo "$data" | jq -r '.categories.achtergrond')
          nieuws=$(echo "$data" | jq -r '.categories.nieuws')
          reportage=$(echo "$data" | jq -r '.categories.reportage')
          message="In $month heb je $luistertijd naar Kleine Boodschap kunnen luisteren:\nInterview: $interview\nAchtergrond: $achtergrond\nNieuws: $nieuws\nReportage: $reportage\n#kleineboodschap"
          echo "message=$message" >> $GITHUB_OUTPUT

      - name: Post message to Bluesky
        uses: myConsciousness/bluesky-post@v5
        with:
          text: ${{ steps.compose.outputs.message }}
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{ secrets.BLUESKY_PASSWORD }}
          retry-count: 5