name: Post monthly Kleine Boodschap stats to Bluesky

on:
  workflow_dispatch:   # Handmatige trigger
  schedule:
    - cron: '50 8 1 * *' # Elke 1e van de maand om 08:50 UTC = 10:50 CEST

jobs:
  post-bluesky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Debug episodes.json presence en inhoud
        run: |
          echo "Inhoud van episodes.json:"
          cat episodes.json

      - name: Compose message from episodes.json
        id: compose
        run: |
          maand=$(date --utc -d '1 day ago' +'%B %Y' -d '-1 month' | sed 's/January/januari/;s/February/februari/;s/March/maart/;s/April/april/;s/May/mei/;s/June/juni/;s/July/juli/;s/August/augustus/;s/September/september/;s/October/oktober/;s/November/november/;s/December/december/')
          
          categories=$(jq -r --arg maand "${maand}" '
            map(select(.datum | startswith(("'"${maand:0:4}"'") + "-" + ("'"${maand:3:2}"'")))) | 
            group_by(.categorie) | 
            map({key: .[0].categorie, value: (map(.tijd|tonumber) | add)}) | 
            from_entries
          ' episodes.json)

          interview=$(echo $categories | jq -r '.interview // 0')
          achtergrond=$(echo $categories | jq -r '.achtergrond // 0')
          nieuws=$(echo $categories | jq -r '.nieuws // 0')
          reportage=$(echo $categories | jq -r '.reportage // 0')

          to_uur_min() {
            local m=$1
            printf "%du %dm" "$((m / 60))" "$((m % 60))"
          }

          interview_fmt=$(to_uur_min $interview)
          achtergrond_fmt=$(to_uur_min $achtergrond)
          nieuws_fmt=$(to_uur_min $nieuws)
          reportage_fmt=$(to_uur_min $reportage)

          totaal=$(($interview + $achtergrond + $nieuws + $reportage))
          totaal_fmt=$(to_uur_min $totaal)

          bericht="In ${maand} heb je ${totaal_fmt} naar Kleine Boodschap kunnen luisteren:
          Interview: ${interview_fmt}
          Achtergrond: ${achtergrond_fmt}
          Nieuws: ${nieuws_fmt}
          Reportage: ${reportage_fmt}
          #kleineboodschap"

          echo "message=$bericht" >> $GITHUB_OUTPUT

      - name: Post message to Bluesky
        uses: myConsciousness/bluesky-post@v5
        with:
          text: ${{ steps.compose.outputs.message }}
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{ secrets.BLUESKY_PASSWORD }}
          retry-count: 5
